serviceName: app-scale-scheduler-service
servicePort: 8080

image:
  repository: asia.gcr.io/airwallex/app-scale-scheduler-service
  tag:

replicaCount: 3

cloudProvider:
  platform:
  region:

resources:
  limits:
    cpu: 2500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

environment:

secretEnvironment: